name: Telerik-Github-Actions-Practice08
env:
WORKSPACE_ENVIRONMENT_VARIABLE:'custom workspace envirionment variable'
on: [push]
jobs:
pre-build:
env:
JOB_ENVIRONMENT_VARIABLE: 'CUSTOM JOB ENVIRONMENT VARIABLE FOR UBUNTU"
runs-on:ubuntu-latest
steps:
-run: echo " The job was automatically triggered by a $ {{ github.event_name }} event.'
-name: Print custom environment variables from ubuntu-latest
env:
STEP_ENVIRONMENT_VARIBLE: ' custom step environment variable for bash"
run: |
echo "accessing environment variable in run command"
echo "$WORKSPACE_ENVIRONMENT_VARIABLE"
echo "$JOB_NVIRONMENT_VARIABLE"
echo "$STEP_ENVIRONMENT_VARIABLE"
